api_key: 'key-7759e660806111fc98cc94d8a40c2e7f'
domain: 'heroku.com'
username: 'postmaster@stark-savannah-36676.herokuapp.com'
password: '59c5959fa3b13921a89639dea244d366'
gmail_username: 'roynilsson87@gmail.com'
gmail_password: 'tr0113k4tt3n$'
